= Trabalho 2, Entrega 1

== Definição do Time

* Alex Peral
* Fabio Leal
* Felipe Fonseca
* Paulo Jerônimo
* Renan Filgueiras
* Sigfredo Rocha

== Briefing do projeto

Atualmente muito se tem falado sobre a corrupção no governo brasileiro, uma parte da população começou a acompanhar, cobrar e fiscalizar na medida do possível o uso do dinheiro público. Um dos grandes problemas é a dificuldade de realizar denúncias e acompanhar o resultado desta, onde muitas vezes o sentimento de impunidade permanece no ar. Possibilitar uma forma mais simplificada de denúncias / reclamações onde a confirmação por vários usuários pode levar a um resultado mais efetivo junto a um órgão responsável auxilia como motivação para novos reportes e combate a corrupção. A solução proposta é a criação de um sistema para que os cidadãos do Distrito Federal possam reportar possíveis casos de corrupções, juntamente com informações disponíveis de dados de empresas provedoras de serviços ao governo a fim de realizar um mapa da corrupção do Distrito Federal.

== Personas: 
* Militantes virtuais (redes sociais)
* Empresários (interessados em licitações)
* Vem p/ rua (Militantes que vão para a rua efetivamente)
* Testemunhas (de atos de corrupção)

== Plano de entregas semanais

* 24-06-2016 - Definição de personas, reformulação do plano de entregas
* 01-07-2016 - Definição da solução, validação com o usuário
* 08-07-2016 - Protótipo
* 15-07-2016 - Finalizar a validação do protótipo e fazer a entrega final

== Atividades do projeto

* https://trello.com/b/oSCeJeya/projeto-de-combate-a-corrupcao
